<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<UserSecretsId>770f75ee-21a8-4a5a-a762-dc6091f378bc</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SBus.Application\SBus.Application.csproj" />
		<ProjectReference Include="..\SBus.Infrastructure\SBus.Infrastructure.csproj" />
	</ItemGroup>
</Project>
